version: "3.7"

services:
  cyber-physical-webapp:
    container_name: sample-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - '.:/home/app'

